export default {
  products: [
    {
      id: 1,
      name: "Apple iPhone 11",
      price: 680.95,
      category: "iphone",
      image: "images/products/iPhone/iphone1.jpeg",
      numReviews: "8",
      rating: 4,
      countInStock: 12,
    },
    {
      id: 2,
      name: "samsung s20",
      price: 600.95,
      category: "samsung",
      image: "images/products/sumsung/samsung1.jpeg",
      numReviews: "8",
      rating: 3,
      countInStock: 6,
    },
    {
      id: 3,
      name: "Sony WH-CH510",
      price: 140.95,
      category: "headphone",
      image: "images/products/headphone/headphone1.jpeg",
      numReviews: "8",
      rating: 5,
      countInStock: 10,
    },
    {
      id: 4,
      name: "Apple iPhone 12",
      price: 620.95,
      category: "iphone",
      image: "images/products/iPhone/iphone2.jpeg",
      numReviews: "8",
      rating: 2,
      countInStock: 8,
    },
    {
      id: 5,
      name: "samsung s9",
      price: 700.95,
      category: "samsung",
      image: "images/products/sumsung/samsung2.jpeg",
      numReviews: "8",
      rating: 3,
      countInStock: 9,
    },
    {
      id: 6,
      name: "Sony WH-CGD20",
      price: 109.95,
      category: "headphone",
      image: "images/products/headphone/headphone2.jpeg",
      numReviews: "4",
      rating: 1,
      countInStock: 8,
    },
    {
      id: 7,
      name: "Apple iPhone 8",
      price: 480.95,
      category: "iphone",
      image: "images/products/iPhone/iphone3.jpeg",
      numReviews: "8",
      rating: 5,
      countInStock: 12,
    },
    {
      id: 8,
      name: "samsung s10",
      price: 600.95,
      category: "samsung",
      image: "images/products/sumsung/samsung3.jpeg",
      numReviews: "8",
      rating: 4,
      countInStock: 6,
    },
    {
      id: 9,
      name: "Sony we-52",
      price: 240.95,
      category: "headphone",
      image: "images/products/headphone/headphone3.jpeg",
      numReviews: "8",
      rating: 3,
      countInStock: 10,
    },
    {
      id: 10,
      name: "Apple iPhone X",
      price: 720.95,
      category: "iphone",
      image: "images/products/iPhone/iphone4.jpeg",
      numReviews: "8",
      rating: 5,
      countInStock: 8,
    },
    {
      id: 11,
      name: "samsung note",
      price: 500.95,
      category: "samsung",
      image: "images/products/sumsung/samsung4.jpeg",
      numReviews: "8",
      rating: 4,
      countInStock: 9,
    },
    {
      id: 12,
      name: "Sony WH-770",
      price: 189.95,
      category: "headphone",
      image: "images/products/headphone/headphone4.jpeg",
      numReviews: "4",
      rating: 4,
      countInStock: 8,
    },
  ],
};
